### ISSUE TITLE
can't find std::cerr symbol?

### ISSUE THREAD

**Issue by dmargala** [rmjarvis/TreeCorr#25]
I'm having some trouble with TreeCorr on my laptop. I've poked around a bit but I'm still not sure what the problem is.

Here is the message I get when I try to run `corr2`:

```
Traceback (most recent call last):
  File "/Users/daniel/anaconda/bin/corr2", line 17, in <module>
    import treecorr
  File "/Users/daniel/anaconda/lib/python2.7/site-packages/treecorr/__init__.py", line 18, in <module>
    from .config import read_config, set_omp_threads
  File "/Users/daniel/anaconda/lib/python2.7/site-packages/treecorr/config.py", line 344, in <module>
    _treecorr = numpy.ctypeslib.load_library('_treecorr',os.path.dirname(__file__))
  File "/Users/daniel/anaconda/lib/python2.7/site-packages/numpy/ctypeslib.py", line 123, in load_library
    return ctypes.cdll[libpath]
  File "/Users/daniel/anaconda/lib/python2.7/ctypes/__init__.py", line 440, in __getitem__
    return getattr(self, name)
  File "/Users/daniel/anaconda/lib/python2.7/ctypes/__init__.py", line 435, in __getattr__
    dll = self._dlltype(name)
  File "/Users/daniel/anaconda/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/daniel/anaconda/lib/python2.7/site-packages/treecorr/_treecorr.so, 6): Symbol not found: __ZSt4cerr
  Referenced from: /Users/daniel/anaconda/lib/python2.7/site-packages/treecorr/_treecorr.so
  Expected in: dynamic lookup
```

demangled symbol name:

```
$ c++filt __ZSt4cerr
std::cerr
```

Shared library report:

```
$ otool -L /Users/daniel/anaconda/lib/python2.7/site-packages/treecorr/_treecorr.so
/Users/daniel/anaconda/lib/python2.7/site-packages/treecorr/_treecorr.so:
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1197.1.1)
	/usr/lib/libgcc_s.1.dylib (compatibility version 1.0.0, current version 2577.0.0)
```

I'm using anaconda python on OS X 10.9.5 and I used pip to install TreeCorr.

**Comment by rmjarvis** [comment]
Daniel, Is this still an issue for you?  Did you give up on this, or did you eventually figure out a way to get the right compiler to be used for the C++ linking?

Just wondering if I should leave this issue open or close it...

**Comment by dmargala** [comment]
I think I gave up on this but it appears that I can run `corr2` without getting that error now. I also ran the unit tests and no problems there either.

**Comment by rmjarvis** [comment]
Cool.  Ok.  Feel free to reopen if it recurs in some environment.
