### ISSUE TITLE
Error in unit tests

### ISSUE THREAD

**Issue by tmcclintock** [rmjarvis/TreeCorr#42]
I just reinstalled and went to run the nosetests. On one of them I recieved an IOError. Here is the whole output related to that unit test:
Starting process NN auto-correlations for cat data/nn_list_rand2.dat.
Using 4 threads.
Starting 39 jobs.
.......................................
Done RR calculations.
Writing NN correlations to output/nn_list1.out
file_type assumed to be ASCII from the file name.
Traceback (most recent call last):
  File "/home/tom/anaconda2/bin/corr2", line 4, in <module>
    __import__('pkg_resources').run_script('TreeCorr==3.2.3', 'corr2')
  File "/home/tom/anaconda2/lib/python2.7/site-packages/setuptools-19.6.2-py2.7.egg/pkg_resources/__init__.py", line 724, in run_script
  File "/home/tom/anaconda2/lib/python2.7/site-packages/setuptools-19.6.2-py2.7.egg/pkg_resources/__init__.py", line 1649, in run_script
  File "/home/tom/anaconda2/lib/python2.7/site-packages/TreeCorr-3.2.3-py2.7-linux-x86_64.egg/EGG-INFO/scripts/corr2", line 105, in <module>
    main()
  File "/home/tom/anaconda2/lib/python2.7/site-packages/TreeCorr-3.2.3-py2.7-linux-x86_64.egg/EGG-INFO/scripts/corr2", line 102, in main
    treecorr.corr2(config, logger)
  File "/home/tom/anaconda2/lib/python2.7/site-packages/TreeCorr-3.2.3-py2.7-linux-x86_64.egg/treecorr/corr2.py", line 227, in corr2
    dd.write(config['nn_file_name'],rr,dr,rd)
  File "/home/tom/anaconda2/lib/python2.7/site-packages/TreeCorr-3.2.3-py2.7-linux-x86_64.egg/treecorr/nncorrelation.py", line 523, in write
    file_name, col_names, columns, prec=prec, file_type=file_type, logger=self.logger)
  File "/home/tom/anaconda2/lib/python2.7/site-packages/TreeCorr-3.2.3-py2.7-linux-x86_64.egg/treecorr/util.py", line 55, in gen_write
    gen_write_ascii(file_name, col_names, columns, prec=prec)
  File "/home/tom/anaconda2/lib/python2.7/site-packages/TreeCorr-3.2.3-py2.7-linux-x86_64.egg/treecorr/util.py", line 86, in gen_write_ascii
    numpy.savetxt(file_name, data, fmt=fmt, header=header)
  File "/home/tom/anaconda2/lib/python2.7/site-packages/numpy/lib/npyio.py", line 1096, in savetxt
    fh = open(fname, 'w')
IOError: [Errno 2] No such file or directory: 'output/nn_list1.out'
EReading input file data/nn_perp_data.dat
   file_type assumed to be ASCII from the file name.
   nobj = 100000
nbins = 5, min,max sep = 20..32.9744, bin_size = 0.1

It looks like it couldn't find the output file. The rest of the unit tests proceeded to run after that, however eventually it failed due to a seg fault. Here is the text related to that failure:

Starting process NNN cross-correlations
Using 4 threads.
Building NField
Starting 38 jobs.
..Segmentation fault (core dumped)

I ran this twice and it failed both times, and I then ran it again from a new terminal, and it also failed there. Let me know if you need any other information related to this.

**Comment by rmjarvis** [comment]
It's trying to write a file in the output directory.  So probably you just need to `mkdir output`.  I think I already ran into this and fixed it on master (by including output/.gitignore in the repo), but I guess I hadn't done that yet by 3.2.3.

As for the seg fault, I recently found a system that does this for test_nnn.py, and I've started looking into it.  It seems to happen when doing NNN correlations with a list of input files (rather than just 1 file).  I haven't yet fixed it though.

**Comment by rmjarvis** [comment]
The seg fault bug is fixed on master.  27c5cce  It was only a bug for 3-point correlations, and even then a pretty rare numerical condition that could lead to a nan (which I now guard against).  

I also made it so the write commands will make a directory if necessary to avoid the IOError on write if the directory doesn't exist.  9fed7ebc864fc5853b0a3b170d73803a6c95cb43

Thanks for the report Tom.

**Comment by tmcclintock** [comment]
Thanks, Mike!
